#include "Metin2TorrentConsole.h"
#include "TorrentPatchEvent.h"

DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_PROGRESS )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_SPAWNED )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_FINISHED )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_READYFORGAMESTART )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_ERROR )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_NOTICE )
DEFINE_EVENT_TYPE( wxEVT_TORRENT_PATCH_CONFIG )

IMPLEMENT_DYNAMIC_CLASS(wxTorrentPatchProgressEvent, wxEvent)
IMPLEMENT_DYNAMIC_CLASS(wxTorrentPatchNotifyEvent, wxEvent)
IMPLEMENT_DYNAMIC_CLASS(wxTorrentPatchConfigEvent, wxEvent)